package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    cleanup {
        expect {
            keepRule {
                id = "KEEP_RULE_1"
                keepAtLeast = days(14)
                dataToKeep = historyAndStatistics {
                    preserveArtifacts = all()
                }
            }
        }
        update {
            keepRule {
                disabled = true
                id = "KEEP_RULE_1"
                keepAtLeast = days(14)
                dataToKeep = historyAndStatistics {
                    preserveArtifacts = all()
                }
            }
        }
        expect {
            keepRule {
                id = "KEEP_RULE_2"
                keepAtLeast = builds(1)
                dataToKeep = historyAndStatistics {
                    preserveArtifacts = all()
                }
                applyPerEachBranch = true
            }
        }
        update {
            keepRule {
                disabled = true
                id = "KEEP_RULE_2"
                keepAtLeast = builds(1)
                dataToKeep = historyAndStatistics {
                    preserveArtifacts = all()
                }
                applyPerEachBranch = true
            }
        }
    }
}
